### ISSUE TITLE
Package does not exist error 

### ISSUE THREAD

**Issue by tanveersingh10** [nus-cs2103-AY2324S1/forum#66] opened 2023-09-01 04:55 UTC
Hey guys I've been stuck with this error for really long and can't make progress

This is my project structure below. I keep getting constant errors saying that the packages don't exist. I'm very sure I included the package duke / package duke.exceptions declaration at the top of every file. I believe I'm also importing correctly. The javac directory is my source root and I have 3 packages: duke, duke.exceptions and duke.tasks. Would appreciate any help.

```
└── java
    └── duke
        ├── Duke.class
        ├── Duke.java
        ├── Storage.class
        ├── Storage.java
        ├── TaskManager.class
        ├── TaskManager.java
        ├── UI.class
        ├── UI.java
        ├── exceptions
         │   ├── DukeException.class
         │   ├── DukeException.java
         │   ├── InvalidArgumentException.class
         │   ├── InvalidArgumentException.java
         │   ├── StorageException.class
         │   ├── StorageException.java
         │   ├── UnknownCommandException.class
         │   └── UnknownCommandException.java
        └── tasks
            ├── Deadline.class
            ├── Deadline.java
            ├── Event.class
            ├── Event.java
            ├── Task.class
            ├── Task.java
            ├── ToDo.class
            └── ToDo.java
```
            
            
       Duke.java:3: error: package duke.exceptions does not exist
import duke.exceptions.InvalidArgumentException;
                      ^
Duke.java:4: error: package duke.exceptions does not exist
import duke.exceptions.UnknownCommandException;
                      ^
Duke.java:5: error: package duke.exceptions does not exist
import duke.exceptions.DukeException;
                      ^
Duke.java:6: error: package duke.tasks does not exist
import duke.tasks.Task;
                 ^
Duke.java:7: error: package duke.tasks does not exist
import duke.tasks.ToDo;
                 ^
Duke.java:8: error: package duke.tasks does not exist
import duke.tasks.Event;
                 ^
Duke.java:9: error: package duke.tasks does not exist
import duke.tasks.Deadline;
                 ^
Storage.java:3: error: package duke.tasks does not exist
import duke.tasks.Task;
                 ^
Storage.java:4: error: package duke.tasks does not exist
import duke.tasks.ToDo;
                 ^

**Comment by damithc** [comment] 2023-09-01 05:05
> └── java
> └── duke
> ├── Duke.class
> ├── Duke.java
> ├── Storage.class
> ├── Storage.java
> ├── TaskManager.class
> ├── TaskManager.java
> ├── UI.class

@tanveersingh10 You need to put this inside a code block. Otherwise the indentation shown will be different from intended. Example:
```
└── java
    └── duke
        ├── Duke.class
        ├── Duke.java
        ├── Storage.class
        ├── Storage.java
        ├── TaskManager.class
        ├── TaskManager.java
        ├── UI.class
        ├── UI.java
```

**Comment by tanveersingh10** [comment] 2023-09-01 05:18
> damithc

Ok sure thanks so much I've fixed that part

**Comment by damithc** [comment] 2023-09-01 05:27
@tanveersingh10 Perhaps push the current code to your fork so that others can try to reproduced the error?
Also specify when does the error happens?

**Comment by nixonwidjaja** [comment] 2023-09-01 11:29
@tanveersingh10 Perhaps restart your IDE and try again

**Comment by lamchenghou** [comment] 2023-09-02 09:28
Hey, with `package duke / package duke.exceptions` as you've mentioned and your project structure, what worked for me was to mark `src/main/java` as your Sources Root directory. This way the packages are identified relative to it. 

If anyone knows how this information is stored when pushed to GitHub / if it is an automatic thing done by IntelliJ, please add on too.

**Comment by lhy-hoyin** [comment] 2023-09-07 06:53
Hello @tanveersingh10 
It looks like your issue has been resolved. If that is the case, perhaps you can close this issue. Otherwise, perhaps you can elaborate on what you still wish to clarify.

**Closed as completed** 2023-09-09 13:42 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
